title:        Alex Singleton
tagline:      'Alex Singleton'
description:  'Professor of Geographic Information Science at the University of Liverpool'
url:    http://www.alex-singleton.com
version:      1.1.1
author:
  name:       Alex Singleton
  email:      alex.singleton@liverpool.ac.uk
permalink:    pretty
pygments:     true
paginate:     6
